### ISSUE TITLE
What does the validate subcommand check

### ISSUE THREAD

**Issue by mbhall88** [alastair-droop/fqtools#20]
Would you be able to elaborate on what criteria the `validate` subcommand checks?

**Comment by alastair-droop** [comment]
The `validate` subcommand processes the input file (or pair of files), and checks for both strict file validity:
- Only allowable characters in the sequence field (as specified by the user);
- Only allowable characters in the quality field (as specified by the defined quality type);
- Sequence and quality lengths match;
- If two files are specified; that they match read count; and
- That the file(s) correctly decompress if compressed.

The above checks are performed by the basic parser (so are performed whenever and action is performed). The `validate` subcommand also checks that the secondary header matches the primary header (if secondary headers are present).

**NB**: There is no attempt to test that corresponding headers across a pair of files match. This is because there is no specific format for marking reads as pair 1 or 2.
